### PR TITLE
The table tests

### PR DESCRIPTION
**Pull request by bertfrees**
I just based this on the other pull request https://github.com/joeha480/dotify/pull/157. Only the last commit has the table tests.

### CODE REVIEW

**Comment by joeha480** [comment]
Could you resolve conflicts? I don't understand why there are conflicts, I haven't modified the DP2 tests that I can recall...

**Comment by bertfrees** [comment]
I mean I added the commit to the dp2-tests branch, but the pull request is for master. There are conflicts because #157 has conflicts. Wait I'll rebase.

**Comment by bertfrees** [comment]
OK there were some conflicts because of the overview file. Probably because when I generate the file there are forward slashes in it and when you generate it has backward slashes.

**Comment by joeha480** [comment]
@bertfrees Thanks! It is been merged.

**Pull request closed without merging**
