### PR TITLE
Add option to insert the print page location

### PR DESCRIPTION
**Pull request by bertfrees**
@joeha480 Does this seem alright to you? Nothing I overlooked?

### CODE REVIEW

**Comment by bertfrees** [comment]
Test at https://github.com/snaekobbi/pipeline-mod-mtm/blob/ae00c153f7413ffaa7b7560c80926933174b54d6/src/test/xprocspec/test_dtbook-to-pef.xprocspec#L488

**Comment by joeha480** [comment]
Is there a reason for not using the pre-existing marker for page number?

**Comment by bertfrees** [comment]
Oh, no not really :) I'll change that. What about my choice to not have the left margin on the cover page? Does that make sense?

**Comment by joeha480** [comment]
Thanks! I have merged this now.

**Pull request closed without merging**
