### PR TITLE
Some more work on formatter tests

### PR DESCRIPTION
**Pull request by bertfrees**

### CODE REVIEW

**Comment by joeha480** [comment]
Have you renumbered the tests? I can't tell what's going on here. Lots of files appear to have changed  into other tests.

**Comment by bertfrees** [comment]
Sorry yes I have. That wasn't so smart. I thought gitk and github would be able to deal with it but they don't. Running `git diff 069d0055c43fcab71c52832bb0b31f9b8639807b...9b83c2cb959b2b62e8670f9543b57d66ebe7ac6f -- pipeline-braille-utils/dotify-utils/dotify-formatter/src/test/xprocspec` in pipeline-mod-braille gives you a better idea of what changed, although I've also done some whitespace cleanup in one of the two files which messes up a part of the diff.

Should I do something? I can try to restore the original numbering if you want. I don't think it matters that much actually. The failing tests still have the same comments (the new tests just say "pagination bugs?")

For the record I do plan to create better labels/filenames. And eventually I'd only like to keep the "test_obfl-to-pef" ones, the ones from "test_format" that are useful and are not covered in test_obfl-to-pef yet should be moved (I can use your help with that).

**Comment by joeha480** [comment]
It's ok. Maybe I can squash the commits, since the changes aren't trackable anyway?

The new tests for pagination are a bit long. It makes it more difficult to find the place where the error is. 
But I'll merge it tomorrow, unless you want to adjust something.

**Comment by bertfrees** [comment]
The new pagination tests are that long because I sometimes test a lot of combinations, to make it very clear in which situations something works and in which situations not. It can make the exact point of the failure hard to spot, but I haven't found a better way to do it yet and at the same time still have the overview.

**Comment by joeha480** [comment]
Merged

**Pull request closed without merging**
